"""S5a it2 — panel MERGE-FAIL mandate (novu root: generated SDK + birth path).

Items under unit-lock:
  1. Content-marker generated detection (FAULTLINE_GENERATED_CONTENT_MARKER,
     default OFF) inside the existing 6.9b channel: Speakeasy one-line
     banner / orval two-line class / @generated marker strip; hand-authored
     files survive; flag OFF → filename-only predicate byte-identical.
  2. Birth-path law: a mega-born PF carries member_files (real residents) +
     split_from lineage; loc>0 && member_files==0 forbidden; single-point
     ledger released == claimed (whole-rehomed dev paths leave the source
     row — the +29.6K/−13.4K double-count class).
  3. Plumbing/dup birth bars: an exact identity twin (topics-v2 ↔ topics)
     MERGES into the existing PF; a head-noun twin (environment-variables ↔
     variables) is REFUSED.
  4. Mega generated-gate: a candidate whose foreign mass is majority
     GENERATED never fires (either prong).
"""

from __future__ import annotations

import os

import pytest

from faultline.pipeline_v2.mega_pf_nav_rehome import (
    _MassOracle,
    run_mega_pf_nav_rehome,
)
from faultline.pipeline_v2.stage_6_9b_generated_strip import (
    GENERATED_CONTENT_ENV_FLAG,
    GeneratedContentProbe,
    generated_content_marker_enabled,
    is_generated_path,
    strip_generated_paths,
)
from faultline.pipeline_v2.transport_handoff import (
    MEGA_DECOMP_ARM_ENV,
    TargetGrainIndex,
)

# reuse the D/E scene stubs
from tests.pipeline_v2.test_s5a_seg_de import (  # noqa: F401
    PF,
    Ctx,
    Dev,
    Fl,
    UF,
    _grain,
    _ri,
    _write,
)

SPEAKEASY = "/*\n * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.\n */\n"
ORVAL = "/**\n * Generated by orval v6.31.0\n * Do not edit manually.\n */\n"
AT_GEN = "// @" + "generated by codegen-tool\n"
PLAIN = "// hand-written module\n"


def _wfile(root, rel, banner, n=6):
    p = root / rel
    p.parent.mkdir(parents=True, exist_ok=True)
    p.write_text(banner + "".join(f"export const x{i} = {i};\n"
                                  for i in range(n)))
    return rel


@pytest.fixture(autouse=True)
def _flags():
    for v in (MEGA_DECOMP_ARM_ENV, GENERATED_CONTENT_ENV_FLAG):
        os.environ.pop(v, None)
    yield
    for v in (MEGA_DECOMP_ARM_ENV, GENERATED_CONTENT_ENV_FLAG):
        os.environ.pop(v, None)


# ── item 1: the content-marker probe ────────────────────────────────────


def test_probe_banner_classes(tmp_path):
    sp = _wfile(tmp_path, "sdk/hooksRetrieve.ts", SPEAKEASY)
    ov = _wfile(tmp_path, "api/client.ts", ORVAL)
    ag = _wfile(tmp_path, "gen/schema.ts", AT_GEN)
    hand = _wfile(tmp_path, "app/page.tsx", PLAIN)
    probe = GeneratedContentProbe(str(tmp_path))
    assert probe.is_generated(sp) is True        # Go-spec one-line class
    assert probe.is_generated(ov) is True        # two-line orval class
    assert probe.is_generated(ag) is True        # @generated marker
    assert probe.is_generated(hand) is False     # hand-authored survives
    assert probe.is_generated("missing/file.ts") is False  # I/O fail-open
    # filename convention still answers without content
    assert probe.is_generated("x/y_pb2.py") is True


def test_probe_banner_must_be_in_head(tmp_path):
    # the marker text buried deep in the file (a docs page QUOTING a
    # banner) is not a banner — only the head window counts.
    rel = "docs/example.ts"
    p = tmp_path / rel
    p.parent.mkdir(parents=True, exist_ok=True)
    p.write_text(PLAIN + ("// filler\n" * 400) + SPEAKEASY)
    probe = GeneratedContentProbe(str(tmp_path))
    assert probe.is_generated(rel) is False


class _F:
    def __init__(self, name, paths, flows=()):
        self.name = name
        self.paths = list(paths)
        self.member_files = []
        self.flows = list(flows)


class _Fl:
    def __init__(self, uuid, paths):
        self.uuid = uuid
        self.name = uuid
        self.paths = list(paths)
        self.entry_point_file = paths[0] if paths else None
        self.line_ranges = [{"path": p, "start_line": 1, "end_line": 5}
                            for p in self.paths]


def test_strip_armed_kills_sdk_flows_off_keeps_them(tmp_path):
    """The novu class, minimally: a dev of banner-generated .ts files whose
    flows enter through them. OFF → v1 filename predicate keeps them
    (byte-ident); ARMED → files strip, the flow and the dev die."""
    gen = [_wfile(tmp_path, f"libs/sdk/src/react-query/op{i}.ts", SPEAKEASY)
           for i in range(3)]
    hand = _wfile(tmp_path, "apps/api/src/app/agents/agents.controller.ts",
                  PLAIN)
    fl_g = _Fl("f-gen", [gen[0], gen[1]])
    fl_h = _Fl("f-hand", [hand])
    sdk_dev = _F("internal-sdk", gen, [fl_g])
    api_dev = _F("agents-api", [hand], [fl_h])
    # OFF leg — MECHANICAL flip migration (2026-07-19 S*-pack, KEY_SCHEMA
    # 32): the v1 filename-only world is now the explicit kill-switch
    # (unset arms the content-marker probe).
    os.environ[GENERATED_CONTENT_ENV_FLAG] = "0"
    feats = [sdk_dev, api_dev]
    flows = [fl_g, fl_h]
    stats = strip_generated_paths(feats, flows, repo_root=str(tmp_path))
    assert stats["paths_removed"] == 0 and stats["features_dropped"] == 0
    assert sdk_dev in feats and fl_g in flows
    # ARMED: the generated dev + its flow die at the source
    os.environ[GENERATED_CONTENT_ENV_FLAG] = "1"
    assert generated_content_marker_enabled()
    gen2 = [_wfile(tmp_path, f"libs/sdk2/src/op{i}.ts", SPEAKEASY)
            for i in range(3)]
    fl_g2 = _Fl("f-gen2", [gen2[0], gen2[1]])
    fl_h2 = _Fl("f-hand2", [hand])
    sdk2 = _F("internal-sdk-2", gen2, [fl_g2])
    api2 = _F("agents-api-2", [hand], [fl_h2])
    feats2 = [sdk2, api2]
    flows2 = [fl_g2, fl_h2]
    stats2 = strip_generated_paths(feats2, flows2, repo_root=str(tmp_path))
    assert stats2.get("content_marker") == 1
    assert stats2["paths_removed"] > 0
    assert sdk2 not in feats2          # emptied dev dropped
    assert fl_g2 not in flows2         # SDK flow died at the source
    assert api2 in feats2 and fl_h2 in flows2   # hand-authored intact


def test_strip_off_flag_is_filename_only():
    # no repo root / flag unset: predicate == v1 is_generated_path exactly
    assert is_generated_path("a/b.pb.go") is True
    assert is_generated_path("libs/internal-sdk/src/react-query/x.ts") is False


# ── items 2+3: birth-path law + dup/plumbing bars ───────────────────────


def _netsec_mint_scene():
    """The Seg A admin-mint scene (3-UF floor mint) with a whole-rehome dev:
    'api-admin' owns ONLY the admin files → whole-dev re-home + birth."""
    A = "backend/routers/admin.py"
    C = "backend/routers/chat.py"
    O = "backend/routers/oauth.py"
    ri = _ri([A, C, O])
    flows = [Fl("f-a1", A), Fl("f-a2", A), Fl("f-a3", A),
             Fl("f-c1", C), Fl("f-c2", C),
             Fl("f-o1", O), Fl("f-o2", O),
             Fl("f-b1", "app/b1.ts"), Fl("f-b2", "app/b2.ts")]
    ufs = [UF("UF-a1", "Manage admins", "netsec", ["f-a1"]),
           UF("UF-a2", "Get admin chats", "netsec", ["f-a2"]),
           UF("UF-a3", "Post admin", "netsec", ["f-a3"]),
           UF("UF-c1", "Browse chats", "netsec", ["f-c1"]),
           UF("UF-c2", "Post chat", "netsec", ["f-c2"]),
           UF("UF-o1", "Connect oauth", "netsec", ["f-o1"]),
           UF("UF-o2", "Revoke oauth", "netsec", ["f-o2"]),
           UF("UF-b1", "B one", "billing", ["f-b1"]),
           UF("UF-b2", "B two", "billing", ["f-b2"])]
    devs = [Dev("api-admin", "netsec", [A]),          # whole-rehome dev
            Dev("api-rest", "netsec", [C, O]),
            Dev("billing-ui", "billing", ["app/b1.ts", "app/b2.ts"])]
    pfs = [PF("netsec", "route:backend/routers/netsec"),
           PF("billing", "route:app")]
    # the source PF ROW also lists the admin file (the double-count trap)
    pfs[0].paths = [A, C, O]
    return devs, pfs, ufs, flows, ri


def test_birth_carries_member_files_and_lineage():
    os.environ[MEGA_DECOMP_ARM_ENV] = "1"
    devs, pfs, ufs, flows, ri = _netsec_mint_scene()
    grain = _grain([], pfs, ri)
    tele = run_mega_pf_nav_rehome(devs, pfs, ufs, flows, ri, Ctx(),
                                  grain_index=grain)
    assert tele["pfs_minted"] == 1
    birth = next(p for p in pfs if getattr(p, "split_from", None))
    assert birth.split_from == "netsec"                     # lineage
    assert birth.member_files, "born PF must carry member_files"
    mf_paths = {m.path for m in birth.member_files}
    assert mf_paths == set(birth.paths)                     # real residents
    # single-point ledger: released == claimed, no double count
    led = tele.get("birth_ledger") or {}
    assert led.get("double_counted") == 0
    assert led.get("unreleased_claims") == 0
    # the whole-rehomed dev's file LEFT the source row (no double count)
    src = next(p for p in pfs if p.name == "netsec")
    assert "backend/routers/admin.py" not in src.paths
    assert "conservation_violations" not in tele


def test_dup_bar_exact_twin_merges():
    """topics-v2-class: a birth whose folded token exactly matches an
    existing PF merges its journeys into it — no twin mint."""
    os.environ[MEGA_DECOMP_ARM_ENV] = "1"
    A = "backend/routers/topics-v2.py"
    B = "backend/routers/chat.py"
    C = "backend/routers/oauth.py"
    ri = _ri([A, B, C])
    flows = [Fl("f-t1", A), Fl("f-t2", A), Fl("f-t3", A),
             Fl("f-c1", B), Fl("f-c2", B),
             Fl("f-o1", C), Fl("f-o2", C),
             Fl("f-x1", "app/topics/one.ts"),
             Fl("f-b1", "app/b1.ts"), Fl("f-b2", "app/b2.ts")]
    ufs = [UF("UF-t1", "Manage topics v2", "netsec", ["f-t1"]),
           UF("UF-t2", "Get topics v2", "netsec", ["f-t2"]),
           UF("UF-t3", "Post topics v2", "netsec", ["f-t3"]),
           UF("UF-c1", "Browse chats", "netsec", ["f-c1"]),
           UF("UF-c2", "Post chat", "netsec", ["f-c2"]),
           UF("UF-o1", "Connect oauth", "netsec", ["f-o1"]),
           UF("UF-o2", "Revoke oauth", "netsec", ["f-o2"]),
           UF("UF-x1", "Browse topics", "topics", ["f-x1"]),
           UF("UF-b1", "B one", "billing", ["f-b1"]),
           UF("UF-b2", "B two", "billing", ["f-b2"])]
    devs = [Dev("api-mixed", "netsec", [A, B, C]),
            Dev("topics-ui", "topics", ["app/topics/one.ts"]),
            Dev("billing-ui", "billing", ["app/b1.ts", "app/b2.ts"])]
    pfs = [PF("netsec", "route:backend/routers/netsec"),
           PF("topics", "route:app/topics"),
           PF("billing", "route:app/b")]
    grain = _grain([], pfs, ri)
    tele = run_mega_pf_nav_rehome(devs, pfs, ufs, flows, ri, Ctx(),
                                  grain_index=grain)
    assert not any(m["cid"].endswith("topics-v2") for m in tele["mints"])
    merged = tele.get("dup_merged") or []
    assert any(d["into"] == "topics" for d in merged)
    homes = {u.id: u.product_feature_id for u in ufs}
    assert homes["UF-t1"] == homes["UF-t2"] == homes["UF-t3"] == "topics"
    assert homes["UF-x1"] == "topics"   # conservation on the receiver


def test_dup_bar_head_noun_twin_refused():
    """environment-variables-class: trailing component matches an existing
    PF ('variables') → the mint is REFUSED (stays, honest)."""
    os.environ[MEGA_DECOMP_ARM_ENV] = "1"
    A = "backend/routers/environment-variables.py"
    B = "backend/routers/chat.py"
    C = "backend/routers/oauth.py"
    ri = _ri([A, B, C])
    flows = [Fl("f-e1", A), Fl("f-e2", A), Fl("f-e3", A),
             Fl("f-c1", B), Fl("f-c2", B),
             Fl("f-o1", C), Fl("f-o2", C),
             Fl("f-v1", "app/variables/one.ts"),
             Fl("f-b1", "app/b1.ts"), Fl("f-b2", "app/b2.ts")]
    ufs = [UF("UF-e1", "Manage env vars", "netsec", ["f-e1"]),
           UF("UF-e2", "Get env vars", "netsec", ["f-e2"]),
           UF("UF-e3", "Post env vars", "netsec", ["f-e3"]),
           UF("UF-c1", "Browse chats", "netsec", ["f-c1"]),
           UF("UF-c2", "Post chat", "netsec", ["f-c2"]),
           UF("UF-o1", "Connect oauth", "netsec", ["f-o1"]),
           UF("UF-o2", "Revoke oauth", "netsec", ["f-o2"]),
           UF("UF-v1", "Browse variables", "variables", ["f-v1"]),
           UF("UF-b1", "B one", "billing", ["f-b1"]),
           UF("UF-b2", "B two", "billing", ["f-b2"])]
    devs = [Dev("api-mixed", "netsec", [A, B, C]),
            Dev("vars-ui", "variables", ["app/variables/one.ts"]),
            Dev("billing-ui", "billing", ["app/b1.ts", "app/b2.ts"])]
    pfs = [PF("netsec", "route:backend/routers/netsec"),
           PF("variables", "route:app/variables"),
           PF("billing", "route:app/b")]
    grain = _grain([], pfs, ri)
    tele = run_mega_pf_nav_rehome(devs, pfs, ufs, flows, ri, Ctx(),
                                  grain_index=grain)
    assert not any("environment-variables" in m["cid"]
                   for m in tele["mints"])
    refused = tele.get("dup_refused") or []
    assert any(d["existing"] == "variables" for d in refused)
    homes = {u.id: u.product_feature_id for u in ufs}
    # refused → the journeys STAY (never guessed into 'variables')
    assert homes["UF-e1"] == homes["UF-e2"] == homes["UF-e3"] == "netsec"


# ── item 4: mega generated-gate ─────────────────────────────────────────


def test_generated_gate_blocks_majority_generated_foreign(tmp_path):
    """A P2 candidate whose FOREIGN mass is majority banner-generated does
    not fire — cutting codegen output is pointless (6.9b is its cure)."""
    os.environ[MEGA_DECOMP_ARM_ENV] = "1"
    AN = "src/app/analytics"
    SUB = "src/app/subscribers"
    # foreign devs = banner-GENERATED big files; core = small hand files
    an = [_wfile(tmp_path, f"{AN}/g{i}.ts", SPEAKEASY, n=200)
          for i in range(3)]
    su = [_wfile(tmp_path, f"{SUB}/g{i}.ts", SPEAKEASY, n=200)
          for i in range(3)]
    core = [_wfile(tmp_path, f"src/core/c{i}.ts", PLAIN, n=2)
            for i in range(10)]
    ri = _ri(an + su + ["src/app/agents/index.ts"])
    flows = [Fl("f-a1", an[0]), Fl("f-a2", an[1]), Fl("f-a3", an[2]),
             Fl("f-s1", su[0]), Fl("f-s2", su[1]), Fl("f-s3", su[2]),
             Fl("f-g1", "src/app/agents/index.ts"),
             Fl("f-g2", "src/app/agents/index.ts"),
             Fl("f-g3", "src/app/agents/index.ts"),
             Fl("f-c1", core[0])]
    ufs = [UF("UF-g1", "View agents", "agents", ["f-g1"]),
           UF("UF-g2", "Run agents", "agents", ["f-g2"]),
           UF("UF-g3", "Edit agents", "agents", ["f-g3"]),
           UF("UF-an", "Browse analytics", "netsec",
              ["f-a1", "f-a2", "f-a3"]),
           UF("UF-su", "Manage subscribers", "netsec",
              ["f-s1", "f-s2", "f-s3"]),
           UF("UF-core", "Run net sec", "netsec", ["f-c1"])]
    devs = [Dev("agents", "agents", ["src/app/agents/index.ts"]),
            Dev("analytics", "netsec", an),
            Dev("subscribers", "netsec", su),
            Dev("netsec-core", "netsec", core)]
    pfs = [PF("agents", "route:src/app/agents"),
           PF("netsec", "route:src/core"),
           PF("analytics", "route:src/app/analytics"),
           PF("subscribers", "route:src/app/subscribers")]

    class C:
        repo_path = str(tmp_path)
        tracked_files: list[str] = []

    grain = _grain([], pfs, ri)
    tele = run_mega_pf_nav_rehome(devs, pfs, ufs, flows, ri, C(),
                                  grain_index=grain)
    rows = {r["pf"]: r for r in tele.get("armed_sources") or []}
    assert rows["netsec"].get("generated_blocked") is True
    assert rows["netsec"]["foreign_generated_share"] > 0.5
    assert "netsec" not in tele["triggered"]
    homes = {u.id: u.product_feature_id for u in ufs}
    assert homes["UF-an"] == homes["UF-su"] == "netsec"   # nothing moved


def test_alite_api_only_birth_refused_ui_birth_lives():
    """a-lite ruling: in a repo WITH a page surface, an API-only birth
    (bridge/change/support/tenant shape) is refused; a birth holding a
    real UI page surface (inbox/integrations shape) lives by evidence."""
    os.environ[MEGA_DECOMP_ARM_ENV] = "1"
    BR = "apps/api/src/app/bridge"
    IN = "apps/api/src/app/inbox"
    INUI = "apps/dashboard/src/pages/inbox-page.tsx"
    ri = [
        # api-class entries (method GET → _is_api_route True)
        {"file": f"{BR}/bridge.controller.ts", "pattern": "/bridge",
         "method": "GET", "surface_scope": "product"},
        {"file": f"{BR}/bridge.service.ts", "pattern": "/bridge/x",
         "method": "POST", "surface_scope": "product"},
        {"file": f"{IN}/inbox.controller.ts", "pattern": "/inbox",
         "method": "GET", "surface_scope": "product"},
        {"file": f"{IN}/inbox.service.ts", "pattern": "/inbox/x",
         "method": "POST", "surface_scope": "product"},
        {"file": f"{IN}/inbox.gateway.ts", "pattern": "/inbox/y",
         "method": "POST", "surface_scope": "product"},
        # PAGE surface: repo_has_pages + inbox UI resident (the UI file
        # rides into the birth via the 'inbox' dev-identity carve)
        {"file": INUI, "pattern": "/inbox-page", "method": "PAGE",
         "surface_scope": "product"},
        {"file": "apps/dashboard/src/pages/home.tsx", "pattern": "/home",
         "method": "PAGE", "surface_scope": "product"},
    ]
    flows = [Fl("f-b1", f"{BR}/bridge.controller.ts"),
             Fl("f-b2", f"{BR}/bridge.service.ts"),
             Fl("f-b3", f"{BR}/bridge.controller.ts"),
             Fl("f-i1", f"{IN}/inbox.controller.ts"),
             Fl("f-i2", f"{IN}/inbox.service.ts"),
             Fl("f-i3", f"{IN}/inbox.gateway.ts"),
             Fl("f-c1", "apps/api/src/app/core.ts"),
             Fl("f-h1", "apps/dashboard/src/pages/home.tsx"),
             Fl("f-h2", "apps/dashboard/src/pages/home.tsx")]
    ufs = [UF("UF-b1", "Manage bridge", "agents", ["f-b1"]),
           UF("UF-b2", "Get bridge", "agents", ["f-b2"]),
           UF("UF-b3", "Post bridge", "agents", ["f-b3"]),
           UF("UF-i1", "Manage inbox", "agents", ["f-i1"]),
           UF("UF-i2", "Get inbox", "agents", ["f-i2"]),
           UF("UF-i3", "View inbox page", "agents", ["f-i3"]),
           UF("UF-c1", "Agents core", "agents", ["f-c1"]),
           UF("UF-h1", "Home one", "home", ["f-h1"]),
           UF("UF-h2", "Home two", "home", ["f-h2"])]
    devs = [Dev("bridge", "agents",
                [f"{BR}/bridge.controller.ts", f"{BR}/bridge.service.ts"]),
            Dev("inbox", "agents",
                [f"{IN}/inbox.controller.ts", f"{IN}/inbox.service.ts",
                 f"{IN}/inbox.gateway.ts", INUI]),
            Dev("agents-core", "agents", ["apps/api/src/app/core.ts"]),
            Dev("home", "home", ["apps/dashboard/src/pages/home.tsx"])]
    pfs = [PF("agents", "route:apps/api/src/app/agents"),
           PF("home", "route:apps/dashboard/src/pages/home")]
    grain = _grain([], pfs, ri)
    tele = run_mega_pf_nav_rehome(devs, pfs, ufs, flows, ri, Ctx(),
                                  grain_index=grain)
    minted = {m["cid"] for m in tele["mints"]}
    # bridge = api-only residents → REFUSED by the a-lite bar
    assert "route:apps/api/src/app/bridge" not in minted
    assert any(r["cid"].endswith("/bridge")
               for r in tele.get("mint_api_only_refused") or [])
    homes = {u.id: u.product_feature_id for u in ufs}
    assert homes["UF-b1"] == homes["UF-b2"] == homes["UF-b3"] == "agents"
    # inbox holds a real UI page resident → LIVES by evidence
    assert "route:apps/api/src/app/inbox" in minted
    assert homes["UF-i1"] != "agents"


def test_mass_oracle_nongen_channel(tmp_path):
    gen = _wfile(tmp_path, "sdk/a.ts", SPEAKEASY, n=50)
    hand = _wfile(tmp_path, "app/b.ts", PLAIN, n=30)
    dev = Dev("mixed", "x", [gen, hand])

    class C:
        repo_path = str(tmp_path)

    o = _MassOracle(C(), [dev])
    assert o.channel == "loc"
    assert o.generated_mass(dev) > 0
    assert o.nongen_mass(dev) == o.dev_mass(dev) - o.generated_mass(dev)
    assert o.nongen_mass(dev) > 0   # the hand file's loc survives
